### ISSUE TITLE
Displaced color markings in compare view

### ISSUE THREAD

**Issue by melandresen** [nilsreiter/CorefAnnotator#114]
Wenn ich Dateien miteinander vergleiche, werden die farblichen Markierungen im Texte nach rechts verschoben angezeigt, s. Screenshot: Die erste Annotation bezieht sich in beiden Texten auf die Spanne "die Konfirmandin".
![bildschirmfoto 2018-05-03 um 11 29 17](https://user-images.githubusercontent.com/37535991/39569651-2389f7ac-4ec6-11e8-96f5-d533da710cf6.png)

**Comment by nilsreiter** [comment]
> Die erste Annotation bezieht sich in beiden Texten auf die Spanne "die Konfirmandin".
Und das sieht beim annotieren auch korrekt aus?

**Comment by melandresen** [comment]
Ja, wenn ich die beiden Daten einzeln öffne, ist alles korrekt.

**Comment by nilsreiter** [comment]
Ich kann das bei der Datei nachvollziehen, aber bei sonst keiner. Habt Ihr das nur bei dieser oder auch bei anderen?

**Comment by nilsreiter** [comment]
Das einzige was mir an der Datei auffällt ist, dass Zeilenumbrüche mit `\r\n` (Windows) kodiert sind, bei unseren Dateien ist das überall nur `\n` (Unix). Glaube aber eigentlich nicht dass es daran liegt, weil es ja in der normalen Ansicht funktioniert.

**Comment by nilsreiter** [comment]
Ha! Das ist tatsächlich das Problem. In der normalen Ansicht werden `\r` durch Leerzeichen ersetzt bevor der Text angezeigt wird. Das habe ich in der Vergleichsansicht vergessen.

**Comment by nilsreiter** [comment]
Fixed in 1.4.4.
