### ISSUE TITLE
File Format Conversion

### ISSUE THREAD

**Issue by melandresen** [nilsreiter/CorefAnnotator#137]
I create a new document in version 1.5.3 from plain text and save it as xmi.gz. When I close it and reopen it with the same version, I am informed that I first need to convert the document from LEGACY to v1. Shouldn't this version create the right format in the first place?

**Comment by nilsreiter** [comment]
Yes, it should. Haven’t created new documents from plain text in a while ...

Thanks for reporting

**Comment by nilsreiter** [comment]
Fixed in 1.5.4
