### ISSUE TITLE
bridging anaphora

### ISSUE THREAD

**Issue by msklvsk** [nilsreiter/CorefAnnotator#140]
My team is considering brat alternatives for a coreference annotation project and I just discovered this tool — got a great first impression. However, I couldn't find the way to annotate bridging anaphora, that is, as in
_We went to see **a concert** last night. **The tickets** were really expensive._

Is there currently a way to annotate such relation, or in general, a relation between clusters?

**Comment by nilsreiter** [comment]
Not right now. There are some vague plans for arbitrary relations between entities, but it’s nowhere near release ready, and I can’t promise that this will be happening very soon.

**Comment by nilsreiter** [comment]
But thanks for asking and considering this tool!
