### ISSUE TITLE
Highlight all mentions of an entity

### ISSUE THREAD

**Issue by melandresen** [nilsreiter/CorefAnnotator#142]
We think it might be convenient to have the possibility to highlight all mentions of an entity, e.g. when clicking on the entity name. We really liked the linking lines between mentions in MMAX2, but I guess a simple highlighting would also be fine.

**Comment by nilsreiter** [comment]
It took a while, but it now looks like this:
![screen shot 2018-10-18 at 17 49 45](https://user-images.githubusercontent.com/12909620/47167222-440c8f00-d2fe-11e8-94e4-09e2ff644a0a.png)

Yellow background color behind mentions. Does that help?

**Comment by melandresen** [comment]
Yes, this looks great!

**Comment by nilsreiter** [comment]
Will be in 1.6.0
