### ISSUE TITLE
Collapse context menu

### ISSUE THREAD

**Issue by andreasvc** [nilsreiter/CorefAnnotator#146]
When using right click to add or remove a coreference to a span, one has to navigate several levels. Instead of having a menu "Annotated entities", how about directly listing those entities? Even better, for each entity, directly give the options show and delete.

On a related note, when I correct a coreference link, it is almost always the case that I want to replace the existing link, instead of having two links for that span. It would therefore save a lot of time if by default adding a new link would replace the existing link for that same span.

**Comment by nilsreiter** [comment]
Thanks for the suggestion, I see what you mean. I think we can improve the menu here.

Correcting a link: We have some use cases were the same span has multiple mention annotations, so I wouldn't include it as a default. But it could be toggleable from the settings menu.
