### ISSUE TITLE
Annotate by keyboard

### ISSUE THREAD

**Issue by andreasvc** [nilsreiter/CorefAnnotator#147]
The help page explains how to add new links by keyboard. Is it also possible to edit/remove existing links? Would be great if everything could be done by keyboard. Also a keyboard shortcut to add keyboard shortcuts would make a lot of sense I think.

**Comment by nilsreiter** [comment]
Yes, that would make a lot of sense, thanks for the suggestion!

**Comment by nilsreiter** [comment]
Will use CMD-K to set the key code (if an entity is selected in the tree on the right)

**Comment by nilsreiter** [comment]
With 1.6, it will be possible to open the context menu with the space bar (with or without having text selected). This then allows deleting mentions via keyboard.

If the input focus in on the tree on the right, you can already delete mentions/entities with CMD-Backspace.
