### ISSUE TITLE
Mention list closed when deleting mentions

### ISSUE THREAD

**Issue by melandresen** [nilsreiter/CorefAnnotator#155]
If I go through all the mentions of an entity and delete one that turns out to be a mistake, the list of mentions is closed. Usually I want to proceed going through the list, so it would be convenient if the list could stay open and the mention after the deleted one was marked.

**Comment by nilsreiter** [comment]
This is actually a side effect of the option to keep the tree sorted at all times. If you disable that, the entity remains open.
