### ISSUE TITLE
Name of groups with more than 3 entities

### ISSUE THREAD

**Issue by melandresen** [nilsreiter/CorefAnnotator#156]
If I create a group of more than 2 entities, only the names of the first two entities are included in the automatically generated name. This is confusing when trying to find the group.

**Comment by nilsreiter** [comment]
What variant do you prefer:
- Peter and Franz and Mary and John
- Peter, Franz et al.
- Peter et al.

Listing all entities will lead to a very long string, so for the tree they definitely need to be abbreviated (but in tooltip and/or search they could appear)

**Comment by melandresen** [comment]
Two aspects are important for my annotators:
1. at least two entity names should be included in the name of the group as e.g. a main character in a novel will appear in many different groups,
2. the name of the group should include the information how many entities are part of this group. Some think that a number is more accessible.
So, our preferred version would be:
    Peter, Franz + 2
or maybe
    Peter, Franz et al. (4)

**Comment by nilsreiter** [comment]
Could look like this:

![screen shot 2019-01-24 at 20 29 41](https://user-images.githubusercontent.com/12909620/51703535-df588300-2016-11e9-9ee3-6be474783067.png)

Good?

**Comment by nilsreiter** [comment]
Small group:

![screen shot 2019-01-24 at 20 59 50](https://user-images.githubusercontent.com/12909620/51705121-0dd85d00-201b-11e9-94f7-873e3fa63325.png)

Large group:
![screen shot 2019-01-24 at 21 00 55](https://user-images.githubusercontent.com/12909620/51705190-36605700-201b-11e9-9dd2-72e312bb673a.png)

Long entity name:
![screen shot 2019-01-24 at 21 01 47](https://user-images.githubusercontent.com/12909620/51705221-4aa45400-201b-11e9-9adc-eb9f79a90f26.png)

Group of entities with long names:
![screen shot 2019-01-24 at 21 02 37](https://user-images.githubusercontent.com/12909620/51705265-71628a80-201b-11e9-807e-c58fe59b0f67.png)

**Comment by melandresen** [comment]
Yes, this looks great. Thanks a lot!
