### ISSUE TITLE
Encoding issue when exporting to TEI

### ISSUE THREAD

**Issue by pagelj** [nilsreiter/CorefAnnotator#157]
When using the "TEI/XML" export function, special characters in entity names are replaced by a dash.
This is especially problematic when a speaker has a special character in their name and the entities of the speaker tags are different.
Examples from *Der sterbende Cato*
```
<sp who="#pharnaces">
<rs ref="#pharnaces"><speaker>PHARNACES.</speaker></rs>
<l>So ists, <rs ref="#dein-vater-hie--sie-eine-r-merinn"><rs ref="#cato"><rs ref="#porcius">dein</rs> Vater</rs> hieß <rs ref="#arsene">sie</rs> eine Römerinn</rs>.</l>
</sp>
```

```
<sp who="#cäsar">
<rs ref="#c-sar"><speaker>CÄSAR.</speaker></rs>
<lg>
<l>Wo will der Eifer hin?</l>
<l>Vergißt man denn, daß ich ein Ueberwinder bin,</l>
<l>Und daß die Römer mich um Gnade bitten müssen?</l>
</lg>
</sp>
```

Version used: 1.6.0
but it was there in previous versions as well

**Comment by nilsreiter** [comment]
When I was implementing this I considered the `who`-attributes to be XML ids, but only later I realised that they are not ... This can be fixed easily.

**Comment by nilsreiter** [comment]
We still want whitespace to be removed, right?

**Comment by pagelj** [comment]
yes that would be ideal I think. So also no whitespace, which would probably be a good idea in general

**Comment by nilsreiter** [comment]
white space will be replaced by a hyphen, the rest stays as it is. Decapitalization has also been removed

XSD:ID also allows certain unicode ranges, which makes a real check more complicated ...
