### ISSUE TITLE
How to use the tools

### ISSUE THREAD

**Issue by Zhenshan-Jin** [nilsreiter/CorefAnnotator#158]
Hi,

Coming across this tool and found out that it is systematically developed. I am wondering do you have a user manual on how to use it? Appreciate it!

Thank you,
Zhenshan

**Comment by nilsreiter** [comment]
Hi,

there are a few help pages accessible from within the tool. They explain the most basic things.
Apart from that, there is also a (short) publication that will be available soon. 

Best
Nils
