### ISSUE TITLE
Automatically rename entities on import

### ISSUE THREAD

**Issue by andreasvc** [nilsreiter/CorefAnnotator#173]
For the use case of correcting coreference output from an existing system, it is useful to have intuitive names for entities. Currently, when you import a CoNLL file, each entity gets an integer ID. Especially for frequent entities, names are much easier to work with, which requires manually renaming them.

My suggestion would be to use the text of the first mention of each entity as label during import. This is often going to provide a useful descriptive label.

**Comment by nilsreiter** [comment]
Good idea. The first or the longest mention?

**Comment by andreasvc** [comment]
I think the first would be best, that's likely how an entity is introduced. Another heuristic is to prefer a mention with upper case (name). Longest might give excessively long descriptions.

**Comment by andreasvc** [comment]
BTW, it occurred to me that it's not necessary to tie this feature to importing. It could be an option in the tool menu so that it can also be applied on an .xmi file after you've already started working.

**Comment by andreasvc** [comment]
Here's a Python implementation: https://gist.github.com/andreasvc/38ce05e4db8e01f9af120a649443256b

**Comment by nilsreiter** [comment]
Nice! It's a good point, it can be included as a menu option.

**Comment by andreasvc** [comment]
Update: looking for upper case mentions is not such a good idea after all, because sentence-initial pronouns are not useful labels. Identifying names is too complicated, and I haven't tried the longest-mention heuristic yet, so I updated my script to stick with the first mention for now.

**Comment by nilsreiter** [comment]
![Screen Shot 2019-03-15 at 18 56 43](https://user-images.githubusercontent.com/12909620/54451879-1bc17900-4754-11e9-9e39-c3c037e1a922.png)

![Screen Shot 2019-03-15 at 18 57 20](https://user-images.githubusercontent.com/12909620/54451916-309e0c80-4754-11e9-8c04-c0eef7e9a582.png)

Longest mention is really not a good idea ;-)
