### ISSUE TITLE
Quick way to delete a mention/link

### ISSUE THREAD

**Issue by andreasvc** [nilsreiter/CorefAnnotator#175]
(I did another round of annotation and wrote down some ideas, so I'll make some issues).

It would be great if a link/mention could be deleted using a keyboard shortcut, because currently this needs to be done with the mouse and requires navigating 2 context menus (or maybe it can be done with the keyboard by searching through the entity list but not easily/quickly).

My suggestion would be: select a span with arrow keys and press `<delete>` key to remove all the mentions/links with that exact span (so not shorter or longer spans). (It could also be ctrl-backspace, but single keystrokes are more ergonomic).

**Comment by nilsreiter** [comment]
Ha, I just noticed yesterday how useful that would be.

**Comment by nilsreiter** [comment]
Ok, we will have:
- `backspace` to delete the mentions that match the selected span exactly. 
- `ctrl-backspace` to delete all mentions within the selected span

If the deleted mentions belong to different entities, they end up as different operations on the undo-list.
