### ISSUE TITLE
Visualize singletons with dashed lines

### ISSUE THREAD

**Issue by andreasvc** [nilsreiter/CorefAnnotator#177]
Idea: when correcting coreference, singletons can be ignored, because they have no links that need to be checked. Therefore, it could be useful to show singleton mentions with a dashed line in the text.

**Comment by nilsreiter** [comment]
Dashed lines are already used for detached parts (relative clauses etc.). I could add a toggle switch to entirely hide them?

**Comment by andreasvc** [comment]
Ahh too bad.
No hiding wouldn't work for me because I do want to correct what should and shouldn't be a mention.
Maybe there's another visual cue we can think of?

**Comment by nilsreiter** [comment]
underlining in light grey would be easy

**Comment by nilsreiter** [comment]
I somehow forgot this, but there will be a toggle in the preferences to enable this. Singletons will then be underlined in gray and dashed.
