### ISSUE TITLE
Select spans by keyboard

### ISSUE THREAD

**Issue by andreasvc** [nilsreiter/CorefAnnotator#185]
The help states: "CorefAnnotator can be used by keyboard. To annotate, mark a text segment using SHIFT and the RIGHT ARROW key."

However, in #182 you re-assigned shift-arrow to jump between mentions.

Could you maybe re-assign jumping between mentions to ctrl-arrow? Selecting spans of text by keyboard using shift-arrow was very useful. It's an explicit goal of CorefAnnotator that everything can be done by keyboard right?

**Comment by nilsreiter** [comment]
Yes it is. 

Sorry, I overlooked that. shift-arrow to select spans was provided by the default text editing view, and I should not have re-assigned that. Thanks for pointing this out.

I'll restore the old function and use alt-arrow for jumping. (ctrl-arrow is otherwise used on OS X).

**Comment by nilsreiter** [comment]
Fixed: https://github.com/nilsreiter/CorefAnnotator/releases/tag/v1.9.1
