### ISSUE TITLE
Not all mentions are underlined

### ISSUE THREAD

**Issue by andreasvc** [nilsreiter/CorefAnnotator#186]
Steps to reproduce:
Annotate as in screenshot, save as .xmi, and re-open. The span for "my" is saved, but not shown (underlined).
It seems to happen commonly with nested spans at the start: [[w1] w2...].

![x](https://user-images.githubusercontent.com/261460/55071023-d07a6500-5087-11e9-81d0-4a2f79ebb127.png)

**Comment by nilsreiter** [comment]
Damn, this worked in 1.8.x ...
