### ISSUE TITLE
Deleting many entities causes (infinite?) loop with 100% CPU usage

### ISSUE THREAD

**Issue by andreasvc** [nilsreiter/CorefAnnotator#192]
With CorefAnnotator 1.9.2.
The xmi file on which I can reproduce this has quite a few empty entities  (100+). I select them all and press delete. Here the application becomes stuck (the context menu doesn't even disappear).

I could share the xmi file privately if you need it to reproduce this issue.

**Comment by nilsreiter** [comment]
Can you send it via email, please? nils.reiter@ims.uni-stuttgart.de

Thanks!

**Comment by andreasvc** [comment]
Will do. I tried to reproduce it at home, where I have Oracle Java 1.8, and there everything works fine. So it must be related to OpenJDK:
```
$ java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```

**Comment by nilsreiter** [comment]
Thanks, I got the file. I can confirm that it works with Oracle JDK, will try with OpenJDK at home.

**Comment by nilsreiter** [comment]
Sorry it took so long, but I can reproduce the problem now on OpenJDK ...

**Comment by nilsreiter** [comment]
The root cause is that if the config option "Keep tree sorted" is on, the ordering of the tree is constantly re-evaluated, which takes some time.

**Comment by andreasvc** [comment]
I ran into this issue again, using OpenJDK 11 with this version: https://github.com/nilsreiter/CorefAnnotator/pull/349

In general, after an hour of annotation, any operation becomes noticeably slow. Changing a link takes about 1 second. Any idea what could be going on?
