### ISSUE TITLE
Can't save file on MacOs Mojave, "Save as..." is necessary

### ISSUE THREAD

**Issue by ariafarmani** [nilsreiter/CorefAnnotator#193]
On CorefAnnotator 1.9.2
MacOs Mojave v. 10.14.4 

The "save" option is greyed out, screenshot of issue is shown below. 

<img width="1280" alt="Screenshot 2019-04-27 at 07 26 08" src="https://user-images.githubusercontent.com/32019444/56845239-87a01100-68be-11e9-9471-923ee3cce10a.png">

**Comment by nilsreiter** [comment]
That's because the file has been imported from some other format (or converted from the old) and has never been saved as a .xmi file before. You have to choose "Save as ..." once and enter a file name. After that, you'll be able to use the "Save" action.

**Comment by ariafarmani** [comment]
My apologies, that did the trick. Thanks :)
