### ISSUE TITLE
Include flags into TEI export

### ISSUE THREAD

**Issue by pagelj** [nilsreiter/CorefAnnotator#238]
Flags should be included in the TEI output, namely

- generic
- abstract

**Comment by nilsreiter** [comment]
Currently, this information can be exported in the CSV export (right click on the entity tree) → "Export Mentions".

```csv
begin,end,surface,entityNum,entityLabel,entityGroup,Generic,Hidden,Ambiguous,Difficult,Non-Nominal
798,830,rebum. Stet clita kasd gubergren,0,takimata,false,true,false,false,false,false
467,483,accusam et justo,0,takimata,false,true,false,true,false,false
247,255,takimata,0,takimata,false,true,false,false,false,false
672,707,tempor invidunt ut labore et dolore,0,takimata,false,true,false,false,false,false
268,279,Lorem ipsum,0,takimata,false,true,false,false,true,false
256,263,sanctus,1,sanctus,false,false,false,false,false,false
```

**Comment by nilsreiter** [comment]
Putting this in the TEI export is not so straightforward, need to add generic feature structures.

**Comment by nilsreiter** [comment]
Also a good question: Where in the document should we add this info? Not all entities are declared in the header. As far as I can tell `<fs>` [can basically go anywhere](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-fs.html). I see two options:

- Add an `<fs>`-element whenever an entity is mentioned first. Then the `<fs>` would go into the `<rs>`-element, like so:
```xml
Und hier, <rs ref="#ein_brief"><fs><f name="specific"><binary value="true"/></f></fs>ein Brief</rs> von der Gräfin Orsina.
```

- Add a section to the tei header in which all feature structures are collected.
