### ISSUE TITLE
Entity list sorting does not work

### ISSUE THREAD

**Issue by pagelj** [nilsreiter/CorefAnnotator#241]
The entity list is randomly sorted, neither switching to alphabetical nor number of mentions sorting works.

Version: CorefAnnotator 1.11.0

```
$ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```

**Comment by nilsreiter** [comment]
Ah I think this is caused by enabling compilation on OpenJDK.
