### ISSUE TITLE
CSV Export 

### ISSUE THREAD

**Issue by nilsreiter** [nilsreiter/CorefAnnotator#252]
CSV Export needs more context

**Comment by nilsreiter** [comment]
Need to solve #76 before

**Comment by NathalieWi** [comment]
CSV export outcome isn't correct. Right context is shown in the next line and not in the column "right context". As a consequence of this, some results get out of place.
![CSVAnsicht](https://user-images.githubusercontent.com/29034382/68458337-d716b080-0202-11ea-9217-b891dfa916aa.JPG)

**Comment by nilsreiter** [comment]
This is because the context contains newline characters, which can't be imported by Excel. Can you check whether the problem persists if you enable the option "Replace newline characters" / "Zeilenumbrüche ersetzen"?

**Comment by NathalieWi** [comment]
Problem is solved with the option "Replace newline character". I'll describe this in the guidlines.
