### ISSUE TITLE
Shortcut display

### ISSUE THREAD

**Issue by nilsreiter** [nilsreiter/CorefAnnotator#256]
It turned out that some people were confused by the shortcut key in front of the label. So we test alternatives.

Test variants
- ~~shortcut before symbol~~: This would be really difficult to implement
- shortcut after word
- shortcut in brackets
- ~~right-aligned in the same row~~: Also complicated

**Comment by nilsreiter** [comment]
Brackets behind the label:
<img width="290" alt="Screenshot 2019-11-06 at 18 14 43" src="https://user-images.githubusercontent.com/12909620/68321086-59975700-00c1-11ea-8885-3e398af602e0.png">

**Comment by nilsreiter** [comment]
Colon behind the label:
<img width="311" alt="Screenshot 2019-11-06 at 18 16 20" src="https://user-images.githubusercontent.com/12909620/68321197-8e0b1300-00c1-11ea-869d-ad55827f8fde.png">

**Comment by nilsreiter** [comment]
I think I'll go for the brackets. Opinions/ideas? @NathalieWi @pagelj

**Comment by pagelj** [comment]
Interesting, for me the current way with the shortcut in front of the label was the most intuitive. I guess in squared brackets is the next best option
