### ISSUE TITLE
Improve entity sort function 

### ISSUE THREAD

**Issue by NathalieWi** [nilsreiter/CorefAnnotator#257]
Maybe place shortcut behind the Entity name.
Example 1: Musik: m (1)

**Comment by nilsreiter** [comment]
Shortcut stuff is in #256, but sorting needs to be case insensitive

**Comment by NathalieWi** [comment]
Sorting is now case insensitive, but in the drop don menu the labels "sort alphabetically" and "sort by mentions" are missing
![sort](https://user-images.githubusercontent.com/29034382/68458612-8489c400-0203-11ea-8df7-964ce2a45a7a.png)

**Comment by nilsreiter** [comment]
fixed.
