### ISSUE TITLE
CSV export context

### ISSUE THREAD

**Issue by nilsreiter** [nilsreiter/CorefAnnotator#261]
If other annotations are available (e.g., lines), it should be possible to restrict the context by those (and not only by character count).

**Comment by NathalieWi** [comment]
- The line export exports one line less than specified. Eg. Export of 5 lines context, exports only 4.
- In the CSV Export Window "Zeichen" is still written in brackets after "Kontextbreite" even if "Zeilen" is chosen for "Gemessen in".

**Comment by nilsreiter** [comment]
> The line export exports one line less than specified. Eg. Export of 5 lines context, exports only 4.

This probably depends on whether the current line also counts ... I add one line.

**Comment by nilsreiter** [comment]
Hm, bei mir funktioniert das. Etwas verwirrend ist vielleicht, dass die Zeile in der die Annotation steht mitgezählt wird. So ungefähr:
```
1 Lorem ipsum dolor sit amet, 
2 consetetur sadipscing elitr, 
3 sed diam [nonumy] eirmod 
4 tempor invidunt ut labore et 
5 dolore magna aliquyam erat, 
6 sed diam voluptua. 
```
Das Zielwort in Zeile 3 mit eckigen Klammern. Wenn Kontextbreite = 2, dann werden Zeilen 2 bis (inkl.) 4 ausgegeben. Zeile 3 ist ja in beide Richtungen halb enthalten ...

**Comment by nilsreiter** [comment]
I think this has been resolved
