### ISSUE TITLE
Show line number in tree view

### ISSUE THREAD

**Issue by NathalieWi** [nilsreiter/CorefAnnotator#266]
B3 asked for this feature, to get a better overview of the annotations in the left column.

**Comment by nilsreiter** [comment]
<img width="308" alt="Screenshot 2019-11-30 at 14 53 07" src="https://user-images.githubusercontent.com/12909620/69901384-2de65480-1381-11ea-84de-9853d5313458.png">

Not sure if I understood correctly. Was this intended?

**Comment by nilsreiter** [comment]
This can also be activated via profile:
```xml
<preference key="CFG_SHOW_LINE_NUMBER_IN_TREE" value="true" />
```

**Comment by nilsreiter** [comment]
If that's not what was meant, please reopen.

**Comment by NathalieWi** [comment]
> <img alt="Screenshot 2019-11-30 at 14 53 07" width="308" src="https://user-images.githubusercontent.com/12909620/69901384-2de65480-1381-11ea-84de-9853d5313458.png">
> 
> Not sure if I understood correctly. Was this intended?

Yes, I think so. This is how B3 described it to me.
