### ISSUE TITLE
Zeilennummern in CSV Export

### ISSUE THREAD

**Issue by NathalieWi** [nilsreiter/CorefAnnotator#268]
Im CSV-Export wird links bei "begin" und "end" die Charakterzahl angegeben. Mit Zeilennummern würde die Orientierung aber leichter fallen.

**Comment by nilsreiter** [comment]
Duplicate of #261

**Comment by nilsreiter** [comment]
This is actually something else.

**Comment by NathalieWi** [comment]
Doesn't work for me. CSV-Export still shows the character numbers.

**Comment by nilsreiter** [comment]
Did you enable the new checkbox?

**Comment by NathalieWi** [comment]
Yes I did.

**Comment by nilsreiter** [comment]
I can't reproduce this. Can you send me the file you got? It should contain two more columns "begin_line" and "end_line", and this works perfectly here.

**Comment by NathalieWi** [comment]
Github doesn't want me to attach a .csv file. So I attach here a screenshot and put the csv-file in the 1.13 folder.
<img width="671" alt="export" src="https://user-images.githubusercontent.com/29034382/70500722-830e2d00-1b1c-11ea-92d8-21dc6c19232e.PNG">


When I launch the programm via command line, there are three warnings:
<img width="900" alt="Command Line" src="https://user-images.githubusercontent.com/29034382/70500572-29a5fe00-1b1c-11ea-8c9c-951b4e631afd.PNG">

**Comment by nilsreiter** [comment]
Ok thanks. I think I know what the problem is.

**Comment by nilsreiter** [comment]
Please try again :)

**Comment by NathalieWi** [comment]
Now it works perfectly! :)
