### ISSUE TITLE
CSV Export unvollständig

### ISSUE THREAD

**Issue by NathalieWi** [nilsreiter/CorefAnnotator#270]
Im CSV-Export fehlen immer wieder Angaben, d.h. Zeilenabschnitte bleiben leer oder tlw. leer.

**Comment by nilsreiter** [comment]
Kannst Du ein reproduzierbares Beispiel dafür nennen?

**Comment by NathalieWi** [comment]
Beispielsweise beim Export der Entität Musik aus Marions annotierter Tristan Datei (im Kooperationsprojekte-Ordner unter B3 > Tübingen > erste Runde). Export ist hier auch als Excel-Datei angehängt und die entsprechenden Stellen sind markiert.
[Musik.xlsx](https://github.com/nilsreiter/CorefAnnotator/files/3904971/Musik.xlsx)

**Comment by nilsreiter** [comment]
hm, in meinem Export ist alles drin. Gibt es die CSV-Datei noch?

**Comment by NathalieWi** [comment]
Habe sie in unseren Teamordner unter 1.13 gelegt.

**Comment by nilsreiter** [comment]
Aber die ist ja neu erzeugt worden (und da fehlt auch nichts). Ich meinte die CSV-Datei, die in die Excel-Datei geladen wurde.

**Comment by NathalieWi** [comment]
Also wenn ich die Datei in Excel in Spalten anzeigen lasse, fehlen da bei mir manche Angaben. Habe das Ergebnis auch im Ordner abgespeichert. Die Datei, die ich hatte als ich den Issue erstellt habe, gibt es leider nicht mehr. Ich kann sie mit der Version 1.12 noch mal erzeugen. Das sollte hoffentlich aufs Gleiche rauskommen.

**Comment by nilsreiter** [comment]
Versuch das mal bitte, bei mir hat das mit 1.12 nämlich nicht geklappt.

**Comment by NathalieWi** [comment]
Jetzt weiß ich woran es liegt. Die Zeilen, bei denen später was fehlt, stehen nicht all Informationen in der CSV-Datei in einer Spalte, sondern in mehreren. Wenn ich das dann umwandle in Excel, gehen die Informationen verloren. Ist es möglich, dass alle Informationen jeder Zeile in der ersten Spalte stehen? Wenn nicht, gibt es bestimmt auch eine Möglichkeit das in Excel anders umzuwandeln.

**Comment by nilsreiter** [comment]
> Ist es möglich, dass alle Informationen jeder Zeile in der ersten Spalte stehen?

Das verstehe ich nicht so ganz. Was meinst Du?

Kern des Problems ist wahrscheinlich, dass das Komma `,` als Spaltentrennzeichen verwendet wird, aber eben auch innerhalb vom Text vorkommt. In den Fällen ist der Inhalt in Anführungszeichen `"` eingeschlossen. Vielleicht muss man Excel das explizit sagen?

**Comment by NathalieWi** [comment]
Hm ich habe nicht das Gefühl, dass es an den Kommata liegt. Davon gibt es in den Versen viele und die werden sonst nicht fälschlicherweise als Spaltentrennzeichen verwendet.
Ich meinte Folgendes: wenn man eine CSV-Datei in Excel öffnet, dann stehen doch alle Informationen einer Zeile in der ersten Excelspalte mit Spaltentrennzeichen aneinandergeschrieben. Oder sehe ich das falsch? 
Beim CSV Export vom Tool stehen aber auch in der B und der C Spalte Informationen (also bevor ich irgendwas damit in Excel gemacht habe, außer die Datei zu öffnen). Ich meinte mit meiner Frage, ob es nicht möglich wäre, alle Informationen in der A Spalte zu haben, dann geht das Umwandeln leichter.

**Comment by nilsreiter** [comment]
Ich bin mir nicht sicher ob ich das verstehe, aber das klingt ja nach danach als hätte Excel das Spaltentrennzeichen nicht richtig erkannt (Excel auf dem Mac funktioniert an der Stelle übrigens sehr anders als unter Windows, deswegen kann ich das nicht selbst sehen).

**Comment by nilsreiter** [comment]
Problem durch Excel-Import, Anleitung wird aktualisiert.
