### ISSUE TITLE
Flags an Annotationen knüpfen

### ISSUE THREAD

**Issue by NathalieWi** [nilsreiter/CorefAnnotator#271]
B3 wünscht sich, dass Flags von Annotationen übernommen werden, wenn diese einer neuen Entität zugeordnet werden. 
-Beispiel: Ein süeze-Beleg hat in der Entität Musik den Marker "ästhetisch" erhalten und wird dann noch der Entität "Sprache und Rede" hinzugefügt. Ideal wäre, wenn auch in dieser zweiten Entität der Marker der Annotation automatisch angezeigt wird und nicht neu hinzugefügt werden muss.

**Comment by nilsreiter** [comment]
Ich fürchte das muss noch etwas warten ...

**Comment by nilsreiter** [comment]
We now have a new preference setting `CFG_STICKY_FLAGS` that can be set via menu or profile. If enabled, toggling a flag on any mention now toggles the same flag on *all* mentions with the same annotation span.

**Comment by nilsreiter** [comment]
```
action.toggle.sticky_flags = Klebende Marker
action.toggle.sticky_flags.tooltip = Klebende Marker kleben an den annotierten Bereichen. Wird ein Marker bei einer Mention geändert, ändern sich auch Marker bei allen anderen Mentions an der gleichen Position
```
If you have a better idea for naming/describing this, I'm all ears :)
