### ISSUE TITLE
Comparison view is incomplete

### ISSUE THREAD

**Issue by NathalieWi** [nilsreiter/CorefAnnotator#279]
- The comparison view doesn't include every annotation. 
- For an example, see the attached file. Annotator MBrue marked "rede" in her file. In the comparison view, her annotations are underlined in blue colour. But "rede" there is only underlined orange.

<img width="784" alt="B3 Vergleich" src="https://user-images.githubusercontent.com/29034382/70615382-90a2e000-1c0c-11ea-9003-d59d38bb0675.PNG">

**Comment by nilsreiter** [comment]
This is in version 1.12, right?

**Comment by nilsreiter** [comment]
Yes, screenshot :)

**Comment by nilsreiter** [comment]
Problem is that 4 out of 5 annotators have marked this. In this case, the four colours should be displayed, instead of just one.
