### ISSUE TITLE
Line numbers change position

### ISSUE THREAD

**Issue by NathalieWi** [nilsreiter/CorefAnnotator#280]
The Parzival-file in folder 1.13 looks normal until you annotate something. Then the line numbers change their position:

![Verszahlen](https://user-images.githubusercontent.com/29034382/70618769-efb82300-1c13-11ea-918c-f0ccc54efa2b.PNG)

**Comment by nilsreiter** [comment]
Only happens when scrolling to the top, interestingly.

**Comment by nilsreiter** [comment]
caused by a NPE in SegmentModel, when no covering segment can be found
