### ISSUE TITLE
Switch to UIMA 3

### ISSUE THREAD

**Issue by nilsreiter** [nilsreiter/CorefAnnotator#300]
UIMA 3 is out for a while, switching would make some things easier.

**Comment by nilsreiter** [comment]
This works in general, but the dependencies to DramaNLP are difficult to handle. We might need a fork of that.

**Comment by pagelj** [comment]
https://github.com/quadrama/DramaNLP will switch to UIMA 3 in version `3.0.0` (scheduled soonish)
