### ISSUE TITLE
CSV and Excel export of the entities is incomplete

### ISSUE THREAD

**Issue by NathalieWi** [nilsreiter/CorefAnnotator#301]
It does not matter whether the entities have been selected individually and exported via "Bearbeiten" > "Export der Erwähnungen" or "Datei" > "Exportieren nach" > "CSV".
Attached are Marions and my export attempt and the source file.
[2020-03-16_vollständiger_Export_Marion.xlsx](https://github.com/nilsreiter/CorefAnnotator/files/4380071/2020-03-16_vollstandiger_Export_Marion.xlsx)
[Parzival_Abgleich_NEU.xmi.gz](https://github.com/nilsreiter/CorefAnnotator/files/4380072/Parzival_Abgleich_NEU.xmi.gz)
[vollständiger_Export_Nathalie.xlsx](https://github.com/nilsreiter/CorefAnnotator/files/4380073/vollstandiger_Export_Nathalie.xlsx)

**Comment by nilsreiter** [comment]
the incompleteness can be seen in the last row, correct?

**Comment by NathalieWi** [comment]
Not only there. Marion wrote to her third try: "Dieses Mal hat es völlig random nur 15 Belege geladen aus den Entitäten „Fragezeichen“ und „Dichtung“, obwohl ich alle ausgewählt hatte."
I think the last line problem is a new problem. If she exports a single entity that has an annotation on the last line, this annoation will not be recognized in the export.

**Comment by nilsreiter** [comment]
Do you have the CSV file that is exported?

**Comment by nilsreiter** [comment]
Will be fixed in 1.14.1
