### ISSUE TITLE
Display of the last verse is missing

### ISSUE THREAD

**Issue by NathalieWi** [nilsreiter/CorefAnnotator#308]
The last verses aren't displayed in the table of contents on the left.
[Rumelant_MB.xmi.gz](https://github.com/nilsreiter/CorefAnnotator/files/4527014/Rumelant_MB.xmi.gz)

**Comment by nilsreiter** [comment]
There is a mismatch in the segmentation layering: The upper layer is shorter (in terms of characters) than the lower. 

@NathalieWi Can you send (or upload) the TEI XML file?  Need to find out how this happened.

**Comment by NathalieWi** [comment]
It says "we don't support that file type". I could send you the file via E-Mail or put it in our Dropbox folder.

**Comment by NathalieWi** [comment]
Additional info: the vers number is also missing in the mention tree on the right when a word of the last verse is annotated.

**Comment by nilsreiter** [comment]
This is likely the same problem. It's actually a bug in the import routine and the conversion from TEI to XMI. I have fixed this now, but it doesn't help with the files that are already imported.

**Comment by nilsreiter** [comment]
... actually, it's more complicated to fix, so it'll have to wait a little longer.
