### ISSUE TITLE
Empty parentheses if no line/segment numbers

### ISSUE THREAD

**Issue by nilsreiter** [nilsreiter/CorefAnnotator#311]
If the file doesn't have line/segment/stanza numbers, the mention list includes empty parentheses:
![Screenshot 2020-04-26 at 09 45 46](https://user-images.githubusercontent.com/12909620/80301164-bb986580-87a2-11ea-8b36-795be2bdd810.png)

**Comment by bkis** [comment]
Closed because the fix found its way into the code base a long time ago.
