### ISSUE TITLE
Cannot find difficult cases and generic mark options

### ISSUE THREAD

**Issue by sabyasachee** [nilsreiter/CorefAnnotator#326]
The help section says that we can mark mentions as difficult and entities as generic. However, I don't see those options anywhere. I am using Java 11.0.8 and JavaFX 11.0.2. I have text files that I need to annotate for coreference chains. Selecting on a mention/entity in the tree view doesn't show me these options anywhere. My OS is macOS 10.15

**Comment by nilsreiter** [comment]
Unfortunately, the help is a bit outdated at this point (thanks for pointing that out). The way to do that now is to create a new flag via menu Tools > Edit Flags. There you can add flags for mentions and entities as you need them. 

If you want to analyse them algorithmically at some point: Make sure to use the same values for "key" across different documents.

**Comment by sabyasachee** [comment]
Thank you. I created the flags and found near-matches to the generic and difficult icons from the MDI icons list.
