### ISSUE TITLE
Install Info for Java Newbs

### ISSUE THREAD

**Issue by arnicas** [nilsreiter/CorefAnnotator#337]
This is embarrassing, but could you add a tiny bit more on the install side?  I don't see the jar file in your repo, so I am not sure what to do to compile and run this with your directories.  Can you add a couple more lines of info?

**Comment by nilsreiter** [comment]
No need to be embarrassed. To find the jar file, you'll have to click on the "Releases" link in the right side bar of the main repository view. It leads to [this page](https://github.com/nilsreiter/CorefAnnotator/releases/tag/v1.14.3). There, you scroll down to the bottom and find a link called "CorefAnnotator-1.14.3-full.jar" -- which is a link to the jar file.

You don't need to compile anything. If you have installed java, double clicking the jar file should suffice.
