### ISSUE TITLE
Change underline color when entity is no longer singleton when "De-emphasize singletons" is enabled

### ISSUE THREAD

**Issue by andreasvc** [nilsreiter/CorefAnnotator#347]
When "De-emphasize singletons" is enabled, singletons are gray. However, adding a mention to a singleton entity means it is no longer a singleton and should trigger a refresh of the underline colors; what happens is that the underline of the original mention remains gray.

Moreover, strange things happen when the "De-emphasize singletons" option is enabled and disabled: several entities in the entity list become invisible, and all singletons get their normal color when the option is disabled, except, oddly, one of the entities which was a singleton but to which I just added a mention.

**Comment by nilsreiter** [comment]
I can reproduce the issue with ex-singletons remaining gray when they get a new mention, but not the other weird things. Does this happen after having added a mention to a singleton entity?

**Comment by andreasvc** [comment]
Yes, the disappearing entities happen when the "De-emphasize singletons" setting is disabled, after having added a singleton mention to an entity. However, I see now that it is only a re-drawing glitch; if I scroll back and forth, the items are there and there is no issue.

![image](https://user-images.githubusercontent.com/261460/111879828-59db7e00-89a8-11eb-8fd0-4bfc99e04607.png)

**Comment by andreasvc** [comment]
The initial issue has been fixed: a singleton with gray underline now gets a color if it is added to an entity. However, if you undo this action, the gray color should come back, but instead the mention which is now a singleton again gets a new color.

**Comment by nilsreiter** [comment]
Ok thanks. I'll look into this.

**Comment by nilsreiter** [comment]
I fixed a few more situations, please check here: https://github.com/nilsreiter/CorefAnnotator/releases/tag/v1.15.0-beta1

**Comment by andreasvc** [comment]
I checked, all fixed now!
