### ISSUE TITLE
shorcut for "show in tree" for selected span

### ISSUE THREAD

**Issue by andreasvc** [nilsreiter/CorefAnnotator#351]
the "show in tree" action is very useful, but as far as I know, can only be done with multiple mouse clicks. would be very useful to have a keyboard shortcut for this.

**Comment by nilsreiter** [comment]
Yes, I understand. One problem is that this applies to the current position, and it might cover multiple mentions. What I can offer is a shortcut that only works in cases it's unique (which is probably your use case anyway?).

**Comment by andreasvc** [comment]
Yes that's fine. In the annotation scheme I use, each mention must only be part of exactly one entity.
