### ISSUE TITLE
Enable longer entity names

### ISSUE THREAD

**Issue by melandresen** [nilsreiter/CorefAnnotator#353]
For the current annotation in Q:TRACK, entity names are usually longer than displayed in the entity list. I would suggest at least twice the number of characters.

**Comment by nilsreiter** [comment]
I'll add an option for that, but I think we should abbreviate the stuff that is entered by annotators anyway.

**Comment by bkis** [comment]
As `UI_MAX_STRING_WIDTH_IN_TREE` is set to `100` in the [current version on **master**](https://github.com/nilsreiter/CorefAnnotator/blob/088d6a9458b51e1782b01a5f0c8248bab170efdb/src/main/java/de/unistuttgart/ims/coref/annotator/Constants.java#L199), I assume this issue has already been addressed?

**Comment by melandresen** [comment]
Yes, the current setting is fine for our annotations.

**Comment by bkis** [comment]
Cool. So right now we abbreviate (view-wise) at >100 characters and people have the possibility to increase the width of the tree view to their liking. I think the optimal solution would be to dynamically abbreviate the label according to the current width of the tree view, but if this feature is really ever wanted, it should have its own issue. Also, I hereby predict implementing this would be a small nightmare anyway :wink: 
I will close this issue in an attempt to tidy up the list a bit. Thank you for replying!
