### ISSUE TITLE
View mentions in order of appearance

### ISSUE THREAD

**Issue by melandresen** [nilsreiter/CorefAnnotator#356]
I guess this does not make much sense for the annotations the tools is originally designed for. However, for our current annotation project, it would be helpful if there was a way to see the annotated mentions in the order of appearance in the text. This is, of course, in conflict with the entity grouping. If you have a quick idea about this, great. Otherwise, I will continue to workaround using the csv export.

**Comment by nilsreiter** [comment]
Do you mean seeing mentions across different entities? Because within an entity, all mentions should be in textual order.

**Comment by melandresen** [comment]
Yes, I mean across entities. 
I just saw that for our newest annotation scheme, in some texts there is only one mention per entity anyway. In that case the entitities (and consequently the mentions) appear in texual order(, unless you sort them alphabetically), too. If that is true for most of our texts, I would close this issue.

**Comment by nilsreiter** [comment]
If not sorted in a particular way, entities are added at the bottom, I think. If annotators go over the text and add entities, they should be in text order. But if another entity is added later, the order is messed up. 
But I think we could also add a new sorting scheme such that the entities are sorted by the textual order of their first mention.
