### ISSUE TITLE
'Safe and close' doesn't work with plaintext

### ISSUE THREAD

**Issue by michaelgoeggelmann** [nilsreiter/CorefAnnotator#357]
The scenario is that you open a plain text file with the Coref annotator and annotate it. Then I want to save my progress by closing the Coref annotator. I am asked if I want to save before closing. If I click on yes here, it will not be saved (presumably because there is no .xmi.gz file at this point in time).

**Comment by nilsreiter** [comment]
Yes, it would be better if this worked, or at least showed some warning.
