### ISSUE TITLE
Color of mentions in compare mode

### ISSUE THREAD

**Issue by melandresen** [nilsreiter/CorefAnnotator#361]
For most (maybe all) files, the colors in compare mode are confusing. If I understood correctly, the idea is that mentions should have one of three colors (given 2 annotators): grey (match), color 1 for annotator 1 only, color 2 for annotator 2 only. However, there are many colors more (that might correspond to the entity colors in the orignal files).

**Comment by nilsreiter** [comment]
There is a setting that has severe impact on the behavior of the compare view: by default, the view should have the colors you describe. In this case, the view compares only mentions. I.e.: if the span is identical, it's  a match, irrespective of the entity they are assigned to. 

If the setting is turned on, two mentions are only a match if they have the same span and the string of their entities is the same. In this case, we use the Color of the entity.

**Comment by melandresen** [comment]
Okay, I did not see that option. Thanks!
