### ISSUE TITLE
Compare mode: Step through list of mentions?

### ISSUE THREAD

**Issue by melandresen** [nilsreiter/CorefAnnotator#362]
In compare mode, I currenty need to scroll through the file and look out for underlined spans of text in order to find mentions were the annotators agree or disagree. It would be helpful to have something like a list of all mentions that I can click through step by step in order to insect (dis)agreement.

**Comment by nilsreiter** [comment]
In 2.0, you can use alt-arrow keys to step over all mentions in textual order (alt-left, alt-right).
