### ISSUE TITLE
Delete annotations of already saved and then reopened files

### ISSUE THREAD

**Issue by michaelgoeggelmann** [nilsreiter/CorefAnnotator#380]
Scenario: I want to check annotations that have already been made. To do this, I open a annotated file, delete some of the annotations, save and close the file. When I reopen the file, the deleted annotations are restored.

Example file: 

SFB 1391 - Kooperationsprojekte C5 B6\Annotationen\Runde 3 Act and Artefact_July-Aug 2021\Richard Tottel_MG.xmi.ca2z

**Comment by melandresen** [comment]
I just ran into the same problem!

**Comment by melandresen** [comment]
(This is the case for entities as well as mentions.)
