### ISSUE TITLE
Scroll function for flag menu

### ISSUE THREAD

**Issue by michaelgoeggelmann** [nilsreiter/CorefAnnotator#387]
From a certain number of markers, they are no longer displayed in their entirety. This could be solved by a scroll function, see
https://tips4java.wordpress.com/2009/02/01/menu-scroller/

**Comment by michaelgoeggelmann** [comment]
\+ maybe there's a way to sort markers alphabetically, but that just as an addition

**Comment by nilsreiter** [comment]
Can you @michaelgoeggelmann add the profile file that adds the markers? Would need it for testing.

**Comment by michaelgoeggelmann** [comment]
[profile.txt](https://github.com/nilsreiter/CorefAnnotator/files/8947509/profile.txt)
