### ISSUE TITLE
Find marked mentions

### ISSUE THREAD

**Issue by nilsreiter** [nilsreiter/CorefAnnotator#42]
There is currently no easy way to find all mentions marked as difficult.

**Comment by melandresen** [comment]
This is a feature that would be very much appreciated by Hamburg. :)
Currently, we add all the difficult cases to an entitiy called "difficult". However, this is not very elegant and you need to delete these before exporting mentions etc.

**Comment by nilsreiter** [comment]
Undocumented feature: a search for “difficult” or “ambiguous” should show entities that have mentions with these labels.

**Comment by nilsreiter** [comment]
(But its not the same thing, I know)

**Comment by melandresen** [comment]
Somehow I cannot reproduce this mystery feature. You mean searching for it in the entity list, right?

**Comment by pagelj** [comment]
Proposal for a workaround: also mark the entities that contain a difficult markable with the "difficult" symbol. This way it would at least be easier to find such markables.
I also could'nt display all "difficult entities" by searching for "difficult"

**Comment by nilsreiter** [comment]
I think the mystery feature only works for flags on entity level (sorry). I am not sure whether it makes sense to be included in the tree search anyway.
